# Pandas DataFrame Oluşturma ve Özellikleri

In [5]:
# Liste üzerinden DataFrame oluşturma işlemleri

import numpy as np
import pandas as pd

In [3]:
l = [1,2,3,4]
l

[1, 2, 3, 4]

In [8]:
df = pd.DataFrame(l, columns = ['degisken_ismi'])
df

degisken_ismi
0              1
1              2
2              3
3              4

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.axes

[RangeIndex(start=0, stop=4, step=1), Index(['degisken_ismi'], dtype='object')]

In [11]:
df.shape

(4, 1)

In [12]:
df.ndim

2

In [13]:
df.size

4

In [14]:
df.values

array([[1],
       [2],
       [3],
       [4]])

In [17]:
df.head(2)

degisken_ismi
0              1
1              2

In [18]:
df.tail(2)

degisken_ismi
2              3
3              4

In [19]:
# Tek boyutlu Numpy Array'i Üzerinden DataFrame Oluşturmak

In [20]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [22]:
df = pd.DataFrame(a, columns=['degisken_ismi'])
df

degisken_ismi
0              1
1              2
2              3
3              4

In [23]:
# İki boyutlu Numpy Array'i Üzerinden DataFrame Oluşturmak

In [25]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
df = pd.DataFrame(m, columns=['var1','var2','var3'])
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [29]:
df.columns = ('deg1','deg2','deg3')

In [30]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [36]:
df = pd.DataFrame(m, columns=['var1','var2','var3'], index = ['a','b','c'])
df

var1  var2  var3
a     1     2     3
b     4     5     6
c     7     8     9

In [37]:
#Pandas Serilerinden DataFrame Oluşturma

In [38]:
pd.DataFrame(pd.Series([1,2,3,4]), columns=['degisken'])

degisken
0         1
1         2
2         3
3         4

In [42]:
# İki adet pandas serisinden dataframe oluşturma (Sözlük gibi oluşturma)

In [40]:
bir = pd.Series([1,2,3,4])
iki = pd.Series([5,6,7,8])

In [41]:
pd.DataFrame({'degisken1': bir,
             'degisken2': iki})

degisken1  degisken2
0          1          5
1          2          6
2          3          7
3          4          8

In [ ]:
#Sözlük üzerinden Dataframe oluşturma

In [43]:
sozluk = {'reg' : {'RMSE': 10,
                  'MSE': 11,
                  'SSE': 90},
         'loj': {'RMSE': 11,
                  'MSE': 12,
                  'SSE': 91},
         'cart': {'RMSE': 12,
                  'MSE': 13,
                  'SSE': 92}}
sozluk

{'reg': {'RMSE': 10, 'MSE': 11, 'SSE': 90},
 'loj': {'RMSE': 11, 'MSE': 12, 'SSE': 91},
 'cart': {'RMSE': 12, 'MSE': 13, 'SSE': 92}}

In [44]:
pd.DataFrame(sozluk)

reg  loj  cart
MSE    11   12    13
RMSE   10   11    12
SSE    90   91    92