## Farklı boyutlu arraylar ile birlikte çalışmak (Broadcasting)

In [2]:
import numpy as np

a = np.array([1,2,3,])

b = np.array([1,2,3])

a + b

array([2, 4, 6])

In [5]:
m = np.ones((3,3))
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
a 

array([1, 2, 3])

In [7]:
a + m

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

Normalde 1'e 3'lük olan array'i 3'e 3'lük olan array'in üzerine yayarak bu işlemi gerçekleştirdi. Bu işleme Broadcasting deniyor.

In [9]:
a = np.arange(3)
a

array([0, 1, 2])

In [11]:
b = np.arange(3)[:,np.newaxis]
b

array([[0],
       [1],
       [2]])

### Kural 1 : Eğer iki array boyut sayısı olarak birbirinden farklı ise boyutu az olanın boyutuna 1 ekleyerek boyutunu çoğalt.


In [12]:
M = np.ones((2,3))
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
a = np.arange(3)  #A array'ine broadcast işlemi uyguladık.
a

array([0, 1, 2])

In [14]:
a + M

array([[1., 2., 3.],
       [1., 2., 3.]])

### Kural 2 : Eğer eşleşmeyen boyut sayısı varsa 1 olan boyutu diğerinin boyutuna eşitle.


In [16]:
a = np.arange(3).reshape((3,1)) # Matrise dönüştürdük.
a

array([[0],
       [1],
       [2]])

In [17]:
b = np.arange(3)
b

array([0, 1, 2])

In [18]:
a.shape

(3, 1)

In [19]:
b.shape

(3,)

In [20]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Kural 3 : Hala uyuşmazlık varsa hata üret.

In [22]:
m = np.ones((3,2))
m

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
a = np.arange(3)
a

array([0, 1, 2])

In [24]:
m.shape

(3, 2)

In [25]:
a.shape

(3,)

In [27]:
m + a # Yapılamaz

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 