# NumPy Hesaplama İşlemleri

In [2]:
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
#Tek boyutlu arraylerde matematiksel işlemler
a-1

array([-1,  0,  1,  2,  3])

In [4]:
a*5

array([ 0,  5, 10, 15, 20])

In [5]:
a/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [6]:
a ** 2

array([ 0,  1,  4,  9, 16])

In [7]:
a % 2

array([0, 1, 0, 1, 0])

In [8]:
5*(a/2*9)

array([ 0. , 22.5, 45. , 67.5, 90. ])

In [9]:
np.add(a,2) #Toplama

array([2, 3, 4, 5, 6])

In [10]:
np.subtract(a,1) #Çıkarma

array([-1,  0,  1,  2,  3])

In [11]:
np.multiply(a,3) # Çarpma

array([ 0,  3,  6,  9, 12])

In [12]:
np.divide(a,3) #Bölme

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [13]:
np.power(a,3) # Kuvvet alma

array([ 0,  1,  8, 27, 64])

In [14]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [16]:
np.add.reduce(a) # Her bir iterasyondan sonra en sonuncusunu verir

15

In [17]:
np.add.accumulate(a) # Her iterasyonda değişen değerleri görmek için

array([ 1,  3,  6, 10, 15])

In [19]:
a = np.random.normal(0,1,30)
a

array([-0.39508828,  0.08354453, -1.18316966, -0.16486905,  0.37956303,
        0.20183652, -0.79139924, -0.90062631, -1.67034889, -2.19680131,
       -0.70774391, -0.37139186,  1.18965221,  1.09904424, -0.23569784,
        0.91223197,  0.77777561, -0.54202548, -0.30141874,  0.60415228,
       -0.40476469,  0.32302095,  0.84513713, -0.35456492,  0.50471564,
        1.66831018,  0.51670034,  1.18594515,  0.82236157,  2.22888456])

In [20]:
np.mean(a) ## Tüm arrayin ortalaması

0.10409885700133818

In [21]:
np.std(a) #Standart Sapma

0.9569290941019966

In [23]:
np.var(a) # Varyans

0.9157132911388678

In [26]:
np.median(a) # Median değeri

0.14269052620738887

In [28]:
np.min(a)

-2.1968013067898378

In [29]:
np.max(a)

2.2288845635673398

In [ ]:
##NOT : np.nanmean() şeklinde yazarsak eksik değerlere duyarlı oluyor.

In [31]:
a = np.random.normal(0,1, (3,3))
a

array([[ 0.06061099, -0.81368979, -1.74384123],
       [ 0.63316343,  0.77744036, -0.6613004 ],
       [ 0.37341981,  0.44481778,  1.24266107]])

In [32]:
a.sum()

0.3132820269531956

In [33]:
a.sum(axis = 0) #Sütun bazında

array([ 1.06719423,  0.40856836, -1.16248056])

In [34]:
a.sum(axis = 1) # Satır Bazında

array([-2.49692003,  0.74930339,  2.06089867])