# NumPy Giriş


### NOTLAR 

np. (tab) 'a basarak hangi metotları içerdiğini görebiliriz.

?np --> dökümantasyon bilgisine ulaşabiliriz.

who komutu ile hangi değişkenlerin kayıtlı olduğunu görebiliriz.

Numpy Sabitlanmiş tipli arraylere sahiptir. Bu Python listelerinin tiplerini tek tek tutmasının yerine daha az maliyetli olan bir durumdur. Listeler esnek olamasına karşın saklama ve manipülatif işlerde çok maliyetli olmaktadır.

# Numpy Arrayleri Oluşturma

## Listelerden Numpy Array Oluşturma

In [12]:
import numpy as np

a = np.array([1,2,3,4])

b = np.array([2,3,4,5])

a * b


array([ 2,  6, 12, 20])

#### Ön tipli bir array oluşturma

In [19]:
np.array([3.14,2,4.12,6], dtype = 'float32' )

array([3.14, 2.  , 4.12, 6.  ], dtype=float32)

#### Sıfırlardan oluşan bir array oluşturma

In [22]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### İki boyutlu birlerden oluşan bir array oluşturma

In [25]:
np.ones((2,3), dtype  = int)

array([[1, 1, 1],
       [1, 1, 1]])

#### Verilen bir değerden matris ve ya vektör oluşturma

In [26]:
np.full((2,3),9)

array([[9, 9, 9],
       [9, 9, 9]])

#### Doğrusal bir dizin oluşturmak için(0'dan 30'a kadar 2'şer artsın gibi)

In [27]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

#### İki değer arasında belirli bir sayıda değer oluşturma

In [29]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### Dağılımlara göre array oluşturma
Örneğin ortalaması "0" Varyansı "1" olan 3'e 4'lük bir matris oluşturma

In [30]:
np.random.normal(0,1, (3,4))

array([[ 0.84668326, -0.42468045, -0.8825001 ,  0.74715121],
       [ 0.56771837, -0.06219695,  0.02757934,  0.88444005],
       [-0.44034292,  0.06026125, -1.09736019, -0.66762893]])

In [31]:
np.random.randint(1,10, (2,4))

array([[5, 6, 4, 2],
       [2, 1, 6, 6]])

#### Köşegen elemanları "1" olan identity matris oluşturma

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])