# NumPy Biçimlendirme

### NumPy Array Özellikleri

* **ndim:** Boyut Sayısı

* **shape:** Boyut Bilgisi

* **size:** Toplam Eleman Sayısı

* **dtype:** Array Veri Tipi


In [16]:
import numpy as np

a = np.random.randint(10,size = 10)
a.ndim
a.shape
a.size
a.dtype


dtype('int64')

In [24]:
a = np.random.randint(10, size=(5,4))
a

array([[8, 2, 5, 1],
       [7, 8, 4, 3],
       [3, 2, 8, 2],
       [7, 3, 1, 4],
       [7, 5, 8, 3]])

In [25]:
a.ndim

2

In [26]:
a.shape

(5, 4)

In [27]:
a.size

20

In [28]:
a.dtype

dtype('int64')

In [29]:
a = np.random.randint(10, size=(5,4,3))
a

array([[[4, 0, 5],
        [8, 3, 6],
        [1, 0, 5],
        [6, 0, 0]],

       [[3, 1, 4],
        [2, 5, 0],
        [0, 9, 7],
        [0, 4, 8]],

       [[3, 0, 0],
        [7, 1, 4],
        [4, 0, 6],
        [9, 5, 6]],

       [[5, 2, 5],
        [9, 5, 5],
        [8, 4, 9],
        [7, 8, 8]],

       [[4, 4, 0],
        [3, 5, 7],
        [8, 7, 5],
        [5, 9, 1]]])

In [30]:
a.ndim

3

In [31]:
a.shape

(5, 4, 3)

In [32]:
a.size

60

In [33]:
a.dtype

dtype('int64')

## Reshape İfadeleri (Yeniden Şekillendirme)


In [36]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Bir vektörü matrise dönüştürme

In [37]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**ÖNEMLİ BİR NOT** Elimizde bir vektör var fakat matris olmasını istiyoruz.Bunu şu şekilde gerçekleştirebiliriz; 

In [42]:
np.array([1,2,3]).reshape((1,3))

2

Boyutları 2 olan satır ve sütün vektörleri oluşturma

In [44]:
a = np.array([1,2,3])

a[np.newaxis, :] #Satır Vektörü

array([[1, 2, 3]])

In [46]:
a[:, np.newaxis] # Sütun Vektörü

array([[1],
       [2],
       [3]])

### Array Birleştirme İşlemleri

In [47]:
x = np.array([1,2,3])

y = np.array([3,4,5])

In [48]:
#Tek boyutlu  arrayleri birleştirme fonksiyonu

np.concatenate([x,y])

array([1, 2, 3, 3, 4, 5])

In [49]:
z = [1,2,3] # Listeyi de aynı şekilde birleştirebiliyoruz.

In [51]:
np.concatenate([x,y,z])

array([1, 2, 3, 3, 4, 5, 1, 2, 3])

In [53]:
# İki boyutlu arrayleri birleştirme işlemi

a = np.array([[1,2,3],
            [3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [54]:
np.concatenate([a,a]) #Satır bazında birleştirme

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3],
       [3, 4, 5]])

In [55]:
np.concatenate([a,a], axis = 1 ) #Sütun bazında

array([[1, 2, 3, 1, 2, 3],
       [3, 4, 5, 3, 4, 5]])

In [65]:
# Farklı boyutlu arrayleri birleştirme

a = np.array([1,2,3])

b = np.array([[9,8,7],
             [6,5,4]])
a,b

(array([1, 2, 3]), array([[9, 8, 7],
        [6, 5, 4]]))

In [67]:
np.vstack([a,b]) #Satır Bazında(Sütun Boyutları aynı olduğu sürece gerçekleştirilebilir.)

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [60]:
a = np.array([[99],    #Sütun Bazında (SatırBoyutları aynı olduğu sürece gerçekleşir)
             [99]])

np.hstack([a,b])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

### Array Ayırma İşlemleri (Splitting)

In [68]:
x = [1,2,3,4,5,6,7,8,9,10]
x

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [70]:
np.split(x, [3,5])

[array([1, 2, 3]), array([4, 5]), array([ 6,  7,  8,  9, 10])]

In [72]:
a,b,c = np.split(x, [3,5])


(array([1, 2, 3]), array([4, 5]), array([ 6,  7,  8,  9, 10]))

In [73]:
a

array([1, 2, 3])

In [74]:
b

array([4, 5])

In [75]:
c

array([ 6,  7,  8,  9, 10])

In [78]:
m = np.arange(16).reshape(4,4) 

In [79]:
ust, alt = np.vsplit(m, [2]) #Dikey ayırma

In [80]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [81]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
sag, sol = np.hsplit(m,[2]) # Yatay ayırma

In [85]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [86]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### Array Sıralama

In [87]:
v = np.array([4,7,8,2,5,0,3,9,6])
v

array([4, 7, 8, 2, 5, 0, 3, 9, 6])

In [91]:
np.sort(v) # Sıralama sonrası orjinal nesneyi bozmaz.

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

** ÖNEMLİ **

In [89]:
i = np.argsort(v) # Yapılan değişiklik sonrası indexlerde ne gibi bir değişiklik olduğunu gösterir.

In [90]:
i

array([5, 3, 6, 0, 4, 8, 1, 2, 7])

In [92]:
#Daha sonradan bu kaydettiğimiz sıralanmış indeksleri nesnemizi değiştirmeden kullanabiliriz.
v[i]

array([0, 2, 3, 4, 5, 6, 7, 8, 9])